[package]
content = {type = "Playable"}
id = "click_with_easymover_demo"
name = "click_with_easymover_demo"
version = "0.0.1"

[dependencies]
clicks_auto = {path = "../clicks_auto", deployment = "2wUGOtwGA7r5JSru1bFyfq" }
easymover = {path = "../easymover", deployment = "4sa5deBTRKL765LDt9HTKn" }
instant_camera = {path = "../instant_camera", deployment = "74XvuMqfzFeMcu1QZh02Mv" }

[messages.MovePlayer]
description = "A left click from the player sends a Move message to the server"
fields = {pos2 = "Vec2"}
