[package]
content = {type = "Asset"}
id = "ease"
name = "ease"
version = "0.0.1"

[components]
ease_float_a = {type = "F32", attributes = ["Networked", "Debuggable"]}
ease_float_b = {type = "F32", attributes = ["Networked", "Debuggable"]}
ease_float_value = {type = "F32"}
ease_vec2_a = {type = "Vec2", attributes = ["Networked", "Debuggable"]}
ease_vec2_b = {type = "Vec2", attributes = ["Networked", "Debuggable"]}
ease_vec2_value = {type = "Vec2"}
ease_vec3_a = {type = "Vec3", attributes = ["Networked", "Debuggable"]}
ease_vec3_b = {type = "Vec3", attributes = ["Networked", "Debuggable"]}
ease_vec3_value = {type = "Vec3", attributes = ["Debuggable"]}

ease_end_time = {type = "F32", attributes = ["Networked", "Debuggable"]}
ease_start_time = {type = "F32", attributes = ["Networked", "Debuggable"]}

ease_target_translation_of = {type = "EntityId"}

translation_easer = {type = "EntityId"}
