[ember]
id = "a_nice_overhead_camera"
name = "a_nice_overhead_camera"
description = "Spawns a nice overhead camera with configurable components"
version = "0.3.0"

[components]
head_pitch = { type = "F32" }
head_yaw = { type = "F32" }
head_relpos = { type = "Vec3" }

the_nice_camera = { type = "Empty" }
nice_yaw_pitch_tilting = { type = "Vec2" }
nice_yaw_pitch_tilting_base = { type = "Vec2" }

[messages.MouseRay.fields]
origin = "Vec3"
dir = "Vec3"