[package]
name = "flume_test"

edition = "2021"
publish = false
version = "0.0.1"

[dependencies]
ambient_api = { workspace = true }
flume = { version = "0.10.14" }

[[bin]]
name = "client_flume_test"
path = "src/client.rs"
required-features = ["client"]

[[bin]]
name = "server_flume_test"
path = "src/server.rs"
required-features = ["server"]

[features]
client = ["ambient_api/client"]
server = ["ambient_api/server"]
