[ember]
id = "boatblue_playerboat_debug"
name = "boatblue_playerboat_debug"
version = "0.0.1"

[dependencies]
boatblue_boat = { path = "../boatblue_boat" }
boatblue_playerboat = { path = "../boatblue_playerboat" }
boatblue_selfie_camera = { path = "../boatblue_selfie_camera" }