[package]
name = "boatblue_playerboat_debug"

edition = "2021"
publish = false
version = "0.0.1"

[dependencies]
ambient_api = { git = "https://github.com/AmbientRun/Ambient.git", rev = "dfc59e4c33" }

[[bin]]
name = "client_boatblue_playerboat_debug"
path = "src/client.rs"
required-features = ["client"]

[features]
client = ["ambient_api/client"]
server = ["ambient_api/server"]