[package]
content = {type = "Playable"}
id = "click_with_ease_demo"
name = "click_with_ease_demo"
version = "0.0.1"

[dependencies]
clicks_auto = {path = "../clicks_auto"}
ease = {path = "../ease"}

[components.cubes_ease]
description = "What ease ent is managing the cube's position right now?"
type = "EntityId"
