[ember]
id = "boat_game_blue"
name = "BoatGameBlue"
version = "0.0.1"

[dependencies]
# pin_mouseuv = { path = "embers/broadcast-only/pin_mouseuv" }
# # ccamera = { path = "embers/entity-owning/ccamera" }
# uv_debugger = { path = "embers/subscribe-only/uv_debugger" }

# boatblue_selfie_camera = { path = "embers/boatblue_selfie_camera" }
# boatblue_selfie_camera_default = { path = "embers/boatblue_selfie_camera_default" }
boatblue_selfie_camera_mouse_tilt = { path = "embers/boatblue_selfie_camera_mouse_tilt" }
boatblue_boat = { path = "embers/boatblue_boat" }