[ember]
id = "boat_game_blue"
name = "BoatGameBlue"
version = "0.0.1"

[dependencies]
# main game
# boatblue_selfie_camera_mouse_tilt = { path = "embers/boatblue_selfie_camera_mouse_tilt" }
# boatblue_boat = { path = "embers/boatblue_boat" }

# player boat & water plane
playerboat = { path = "embers/boatblue_playerboat" }
water = { path = "embers/boatblue_water" }

# just testing a demo
# demo = { path = "embers/boatblue_matter_demo" }
# demo = { path = "embers/boatblue_boat_demo" }