[ember]
id = "boat_game_blue"
name = "BoatGameBlue"
version = "0.0.1"

[dependencies]
# main game
# boatblue_selfie_camera_mouse_tilt = { path = "embers/boatblue_selfie_camera_mouse_tilt" }
# boatblue_boat = { path = "embers/boatblue_boat" }

# player boat & water plane
playerboat = { path = "embers/boatblue_playerboat" }
playgrid = { path = "embers/boatblue_playgrid" }
# playerboat_debug = { path = "embers/boatblue_playerboat_debug" }
water = { path = "embers/boatblue_water" }
# citygen = { path = "embers/boatblue_citygen_simple" }
trash = { path = "embers/boatblue_scatteredtrash" }

# just testing a demo
# demo = { path = "embers/boatblue_matter_demo" }
# demo = { path = "embers/boatblue_boat_demo" }