[ember]
id = "sac_physics_force"
name = "sac-physics-force"
version = "0.0.1"

[components]
driven_power = { type = "F32", attributes = ["Networked", "Debuggable"] }

[dependencies]
boatblue_selfie_camera = { path = "../../BoatGameBlue/embers/boatblue_selfie_camera" }
scmt = { path = "../../BoatGameBlue/embers/boatblue_selfie_camera_mouse_tilt" }
