[package]
content = {type = "Playable"}
id = "defender_ptt"
name = "defender_ptt"
version = "0.0.1"

[messages.Shoot]
description = "Client-server message: Shooting a particular spot on the ground"
[messages.Shoot.fields]
point = "Vec2"

[components.runner_spawnpos]
attributes = ["Networked", "Debuggable"]
description = "Where did this runner spawn? (ground)"
type = "Vec2"

[components.runner_spawntime]
attributes = ["Networked", "Debuggable"]
description = "When did this runner spawn? (game_time)"
type = "F32"

# todo - components defining runner movement pattern variation

[components.model_of_runner]
description = "Clientside - points to runner which this is visual model of"
type = "EntityId"
