[package]
content = {type = "Playable"}
id = "player_score_display"
name = "player_score_display"
version = "0.0.1"

[components]
player_score = {attributes = ["Debuggable", "Networked"], description = "Player has a score number", type = "U32"}
player_score_position = {attributes = ["Debuggable", "Networked"], description = "Position of the player's score (world)", type = "Vec3"}
score_config_camera = {type = "EntityId"}

[messages.ConfigureCamera]
description = "Configure whether there is a camera. Note that once configured the camera cannot be removed"
[messages.ConfigureCamera.fields]
camera = "EntityId"
