[package]
content = {type = "Asset"}
id = "easymover"
name = "easymover"
version = "0.0.1"

[dependencies]
ease = {path = "../ease", deployment = "3RL5e6HWec4CoLs3NwtGZi"}

[components]
# emover is serverside.
effect_spawn_emover_at = {type = "Vec2"}
emover_landgoal = {attributes = ["Debuggable"], description = "Ground position of emover's goal position, just set this to move", type = "Vec2"}
emover_movespeed = {attributes = ["Networked", "Debuggable"], description = "Ground speed of emover (units per second). Positive values only please.", type = "F32"}

ease_propagate_landpos_to = {attributes = ["Networked", "Debuggable"], description = "Whose landpos to set?", type = "EntityId"}
emover_landpos = {attributes = ["Debuggable"], description = "Ground position of emover", type = "Vec2"}# driven by one of two 'posdriver' components
emover_posdriver_ease = {attributes = ["Networked", "Debuggable"], description = "Ease entity of emover (ease vec2)", type = "EntityId"}

# esprite is clientside.
esprite_landpos = {description = "Clientside: Esprite's ground position", type = "Vec2", attributes = ["Debuggable"]}
esprite_mover = {description = "Clientside: Esprite's emover", type = "EntityId"}
