[ember]
id = "demo_cutefruit"
name = "demo_cutefruit"
version = "0.0.1"

[dependencies]
a_nice_overhead_camera = { path="../a_nice_overhead_camera"}
skatemouse = { path="../skatemouse" }
ww_gen = { path="../ww_gen" }
skatemouse_demo = { path="../skatemouse/demo" }
buoy = { path="../buoy" }

# dans = { path = "../dans_modeling_agency" }

all_blocks_decorated_as_shacks = { path = "../all_blocks_decorated_as_shacks" }

[components]
is_dot = { type = "Empty" }

# 'overhead ui'
score = { type = "U8", attributes = ["Networked", ] }
scorebob_parent = { type = "EntityId" }
scorebob_child = { type = "EntityId" }
scorebob_throb = { type = "F32", attributes = ["Debuggable", ] }