[ember]
id = "boatblue_selfie_camera_demo"
name = "boatblue_selfie_camera_demo"
version = "0.0.1"

[dependencies]
boatblue_selfie_camera = { path = "../boatblue_selfie_camera" }

[components]
pitch_wobbler_time = { type = "F32" }