[package]
content = {type = "Playable"}
id = "relationships"
name = "relationships"
version = "0.0.1"

[components]
rel_fish_follower = {type = "Empty"}# relationship
rel_fishs_body = {type = "Empty"}# relationship
# rel_unspecified = {type = "Empty"}
# relationships = {type = {container_type = "Vec", element_type = "EntityId"}}
fish_swim_dir = {type = "Vec3"}
left_relative = {type = "EntityId"}
right_relative = {type = "EntityId"}
